server:
  port: 8081

managament:
  security:
    enabled: false
  health:
    circiutbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      serviceA:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 3s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState : 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize : 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      serviceA:
        max-attempts: 5
        wait-duration: 10s